from pathlib import Path
import os

MAKES = [
    'AAD',
    'ABARTH',
    'ALFA ROMEO',
    'AUDI',
    'BENTLEY',
    'BMC',
    'BMW',
    'CADILLAC',
    'CHANA',
    'CHANGAN',
    'CHERY',
    'CHEVROLET',
    'CHRYSLER',
    'CITROEN',
    'DACIA',
    'DAEWOO',
    'DAF',
    'DAIHATSU',
    'DATSUN',
    'DODGE',
    'EICHER',
    'ERF',
    'FAW',
    'FERRARI',
    'FIAT',
    'FORD',
    'FOTON',
    'FREIGHTLINER',
    'FUSO',
    'GAZ',
    'GONOW',
    'GWM',
    'HAFEI',
    'HAVAL',
    'HINO',
    'HONDA',
    'HUMMER',
    'HYUNDAI',
    'INFINITI',
    'INTERNATIONAL',
    'ISUZU',
    'IVECO',
    'JAGUAR',
    'JEEP',
    'JINBEI',
    'JMC',
    'KIA',
    'LAMBORGHINI',
    'LAND ROVER',
    'LANDWIND',
    'LEXUS',
    'MACK',
    'MAHINDRA',
    'MAN',
    'MASERATI',
    'MAYBACH',
    'MAZDA',
    'MEIYA',
    'MERCEDES',
    'MINI',
    'MITSUBISHI',
    'NISSAN',
    'OPEL',
    'PETERBILT',
    'PEUGEOT',
    'PORSCHE',
    'POWERLAND',
    'POWERSTAR',
    'PROTON',
    'RENAULT',
    'SAAB',
    'SCANIA',
    'SEAT',
    'SMART',
    'SSANGYONG',
    'SUBARU',
    'SUZUKI',
    'TATA CARS',
    'TATA TRUCK & BUS',
    'TOYOTA',
    'UD TRUCKS',
    'VDL',
    'VOLKSWAGEN',
    'VOLVO',
    'VOLVO BUS',
    'VOLVO TRUCKS',
    'ZOTYE',
]
BASE_DIR = Path(os.path.dirname(__file__))
MONROE_CATALOGUE_PATH = BASE_DIR / 'data' / 'monroe-catalogue-2020-21-za.pdf'
MAPPING_SYSTEM_PATH = BASE_DIR / 'data' / 'Final Mapping Tool Template - 2022 - v2.xlsx'

COLUMN_HEADINGS = [
    'Year',
    'Application',
    'Front Entry Shock',
    'Front Premium Shock',
    'Front Springs',
    'Front Protection kits/ Mounting kits',
    'Front Mounting information',
    'Rear Entry Shock',
    'Rear Premium Shock',
    'Rear Springs',
    'Rear Protection kits/ Mounting kits',
    'Rear Mounting information',
]

PART_COLS = [
    'Front Entry Shock',
    'Front Premium Shock',
    'Front Springs',
    'Front Protection kits/ Mounting kits',
    'Front Mounting information',
    'Rear Entry Shock',
    'Rear Premium Shock',
    'Rear Springs',
    'Rear Protection kits/ Mounting kits',
    'Rear Mounting information'
]

FINAL_COLS = [
    'Make',
    'Model',
    'Check Model',
    'Start Year',
    'End Year',
    'Include Derivatives',
    'Exclude Derivatives',
    'Front Entry Shock',
    'Front Premium Shock',
    'Front Springs',
    'Front Protection kits',
    'Front Mounting kits',
    'Front Mounting information',
    'Rear Entry Shock',
    'Rear Premium Shock',
    'Rear Springs',
    'Rear Protection kits',
    'Rear Mounting kits',
    'Rear Mounting information',
]

COLUMN_MAPPING = {
    'Front Left': 'Front Entry Shock',
    'Front Right': 'Front Entry Shock',
    'Protection Kits Front': 'Front Protection kits',
    'Mounting Kits Front': 'Front Mounting kits',
    'Rear Left': 'Rear Entry Shock',
    'Rear Right ': 'Rear Entry Shock',
    'Protection Kits Rear': 'Rear Protection kits',
    'Mounting Kits Rear': 'Rear Mounting kits',
    'Front Left 1': 'Front Premium Shock',
    'Front Right 1': 'Front Premium Shock',
    'Rear Left    1': 'Rear Premium Shock',
    'Rear Right 1': 'Rear Premium Shock',
}